name: Feature Request
description: Suggest a new feature or enhancement.
title: "feat: "
labels: ["type: feature", "status: needs triage"]
body:
  - type: textarea
    attributes:
      label: Summary
      description: One‑sentence overview of the feature or change.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is this needed?
      description: What problem does this solve? Why is it valuable for users?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      placeholder: |
        e.g., Add a new API method to do X, modify behavior of Y to support Z, etc.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
