name: Create Tag, Release & Publish
on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Read Version from gradle.properties
        id: get_version
        run: |
          VERSION=$(grep '^baseVersion=' gradle.properties | cut -d'=' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Create Tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const version = '${{ steps.get_version.outputs.version }}';
            const tag = `v${version}`;
            const { data: ref } = await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: context.sha
            });
            core.info(`Created tag ${tag} at ${context.sha}`);
      
            

  call-release:
    needs: tag
    uses: ./.github/workflows/release-and-publish.yml
    with:
      tag_name: "v${{ needs.tag.outputs.version }}"
    secrets: inherit