name: PR Snapshot Publish
on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened
      - reopened
    paths:
      - 'modules/**/src/main/**'
      - 'modules/**/build.gradle'
      - 'build.gradle'
      - 'gradle.properties'

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v5
      - name: Setup JDK 24 for Kotlin 2.2.0
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: 'gradle'
      - name: Determine PR Snapshot Version
        id: versioning
        run: |
          BASE_VERSION=$(grep '^baseVersion=' gradle.properties | cut -d'=' -f2)
          PR_NUMBER=${{ github.event.pull_request.number }}
          INCREMENT=$(date +%s)
          SNAPSHOT_VERSION="${BASE_VERSION}-SNAPSHOT-${PR_NUMBER}-${INCREMENT}"
          
          echo "snapshot_version=$SNAPSHOT_VERSION" >> $GITHUB_OUTPUT
          echo "Using snapshot version: $SNAPSHOT_VERSION"
      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew
      - name: Publish PR Snapshot to Maven Central
        run: ./gradlew publishToMavenCentral --stacktrace -Pversion=${{ steps.versioning.outputs.snapshot_version }}
      - name: Comment Snapshot Coordinates on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🆕 **PR Snapshot Published to Maven Central**

            You can test this PR build by adding the following dependencies:

            ```gradle
            implementation "io.github.eventhorizonlab:spi-tooling-annotations:${{ steps.versioning.outputs.snapshot_version }}"
            kapt "io.github.eventhorizonlab:spi-tooling-processor:${{ steps.versioning.outputs.snapshot_version }}"
            ```

            _This comment will be updated automatically if a new snapshot is published for this PR._
          edit-mode: replace
