name: Release and Publish

on:
  workflow_call:

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
      ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
      ORG_GRADLE_PROJECT_gprUser: ${{ github.actor }}
      ORG_GRADLE_PROJECT_gprToken: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK 24 for Kotlin 2.2.0
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: 'gradle'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build Artifacts
        run: ./gradlew clean build --no-daemon --stacktrace

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Maven Central and GitHub Packages
        run: ./gradlew publishAllPublicationsToCentralPortalRepository publishAllPublicationsToGitHubPackagesRepository --no-daemon --stacktrace